// <auto-generated />
namespace RestuarantApp_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta1-30916")]
    public sealed partial class addfirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfirst));
        
        string IMigrationMetadata.Id
        {
            get { return "201410291219132_addfirst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
